# Generated by Django 4.2 on 2025-11-26 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementoNovia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('velos', 'Velos'), ('tocados', 'Tocados'), ('zapatos', 'Zapatos'), ('bolsos', 'Bolsos'), ('joyeria', 'Joyería'), ('accesorios', 'Accesorios'), ('lenceria', 'Lencería')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('imagen_principal', models.URLField()),
                ('imagenes_adicionales', models.TextField(blank=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Complementos de Novia',
            },
        ),
        migrations.CreateModel(
            name='ComplementoNovio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('corbatas', 'Corbatas'), ('pajaritas', 'Pajaritas'), ('gemelos', 'Gemelos'), ('zapatos', 'Zapatos'), ('relojes', 'Relojes'), ('panuelos', 'Pañuelos'), ('cinturones', 'Cinturones'), ('tirantes', 'Tirantes'), ('alfileres', 'Alfileres')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('imagen_principal', models.URLField()),
                ('imagenes_adicionales', models.TextField(blank=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Complementos de Novio',
            },
        ),
        migrations.CreateModel(
            name='TrajeNovio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('tipo', models.CharField(choices=[('esmoquin', 'Esmoquin'), ('traje', 'Traje'), ('chaque', 'Chaqué'), ('smoking', 'Smoking')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('tallas_disponibles', models.CharField(max_length=200)),
                ('imagen_principal', models.URLField()),
                ('imagenes_adicionales', models.TextField(blank=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Trajes de Novio',
            },
        ),
        migrations.CreateModel(
            name='VestidoNovia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('estilo', models.CharField(choices=[('princesa', 'Princesa'), ('sirena', 'Sirena'), ('bohemio', 'Bohemio'), ('linea_a', 'Línea A'), ('minimalista', 'Minimalista'), ('vintage', 'Vintage')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('tallas_disponibles', models.CharField(max_length=200)),
                ('imagen_principal', models.URLField()),
                ('imagenes_adicionales', models.TextField(blank=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vestidos de Novia',
            },
        ),
        migrations.CreateModel(
            name='TareaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('lugar', 'Lugar'), ('catering', 'Catering'), ('invitaciones', 'Invitaciones'), ('vestuario', 'Vestuario'), ('fotografia', 'Fotografía'), ('decoracion', 'Decoración'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tareas de Agenda',
                'ordering': ['fecha', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('lugar', 'Lugar'), ('comida', 'Comida'), ('fotografia', 'Fotografía'), ('vestuario', 'Vestuario'), ('decoracion', 'Decoración'), ('entretenimiento', 'Entretenimiento'), ('papeleria', 'Papelería'), ('otros', 'Otros')], max_length=20)),
                ('tipo_item', models.CharField(choices=[('servicio', 'Servicio'), ('vestido', 'Vestido de Novia'), ('traje', 'Traje de Novio'), ('complemento_novia', 'Complemento Novia'), ('complemento_novio', 'Complemento Novio'), ('personalizado', 'Personalizado')], default='personalizado', max_length=20)),
                ('presupuestado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('complemento_novia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.complementonovia')),
                ('complemento_novio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.complementonovio')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicio')),
                ('traje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trajenovio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to=settings.AUTH_USER_MODEL)),
                ('vestido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vestidonovia')),
            ],
            options={
                'verbose_name_plural': 'Items de Presupuesto',
            },
        ),
    ]
