# Generated by Django 4.2 on 2025-11-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complementonovia_complementonovio_trajenovio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='complemento_novia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.complementonovia'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='complemento_novio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.complementonovio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='traje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.trajenovio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vestido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.vestidonovia'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.servicio'),
        ),
    ]
